
# This file contains all the configurable values for your application, 
# such as image details, replicas, and ingress settings.

# web-app-helm-chart/values.yaml
# Define a custom name for your resources (e.g., web-app)
# Default values for my-webapp
# web-app-helm-chart/values.yaml

replicaCount: 2

image:
  repository: 281695752858.dkr.ecr.us-east-1.amazonaws.com/huggingface-fastapi
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "external-nginx"
  hosts:
    - host: ""  # You can add a domain or NLB DNS here
      paths:
        - path: /
          pathType: Prefix
  tls: []
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
